/*
**	Command & Conquer Generals Zero Hour(tm)
**	Copyright 2025 Electronic Arts Inc.
**
**	This program is free software: you can redistribute it and/or modify
**	it under the terms of the GNU General Public License as published by
**	the Free Software Foundation, either version 3 of the License, or
**	(at your option) any later version.
**
**	This program is distributed in the hope that it will be useful,
**	but WITHOUT ANY WARRANTY; without even the implied warranty of
**	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
**	GNU General Public License for more details.
**
**	You should have received a copy of the GNU General Public License
**	along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

// Runtime-compiled HLSL source for the D3D11 fixed-function-emulation layer
// (RENDERER_PORT.md steps 5/6/7). D3D11Backend feeds these strings to D3DCompile
// at startup. They are a VERBATIM mirror of the human-readable, fxc-consumable
// Shaders/FFVertex.hlsl and Shaders/FFPixel.hlsl - keep all three in sync.
//
// - kFFVertexShaderHLSL: transform + fixed-function per-vertex lighting (step 7)
//   + forward the (lit-or-passthrough) diffuse and two texcoord sets + a
//   view-space fog coordinate.
// - kFFPixelShaderHLSL:  the texture-stage combiner ubershader (one shader
//   parameterized by cbCombiner, looping the active stages) followed by linear/
//   exp fog blending (step 7). The integer op/arg codes it uses mirror the
//   RenderBackendTexOp / RenderBackendTexArg enums in IRenderBackend.h.
//
// Matrix convention (documented in FFVertex.hlsl): WWMath Matrix4x4 is
// column-vector / OpenGL-style, uploaded row-by-row; the VS declares the matrices
// row_major and multiplies mul(matrix, vector).
//
// FIXED-FUNCTION LIGHTING EQUATION (step 7), evaluated per vertex when
// D3DRS_LIGHTING is enabled (LightingEnable != 0):
//
//   litColor.rgb = MatEmissive
//                + MatAmbient   * GlobalAmbient          (ambient term)
//                + sum over active directional lights of
//                      saturate(dot(N, -LightDir_i)) * MatDiffuse * LightDiffuse_i
//
// where MatDiffuse / MatAmbient resolve to either the material constant
// (D3DMCS_MATERIAL) or the interpolated vertex color (D3DMCS_COLOR1), selected by
// DiffuseSource / AmbientSource - mirroring D3DRS_*MATERIALSOURCE. N is the
// world-space normal. When lighting is disabled the vertex diffuse passes through
// unchanged (the pre-step-7 behavior), so every existing combiner/triangle assert
// is unaffected.

#pragma once

static const char kFFVertexShaderHLSL[] =
	"cbuffer cbPerObject : register(b0)\n"
	"{\n"
	"    row_major float4x4 WorldViewProj;\n"
	"};\n"
	"cbuffer cbLighting : register(b1)\n"
	"{\n"
	"    row_major float4x4 World;\n"
	"    row_major float4x4 View;\n"
	"    float4 GlobalAmbient;\n"
	"    float4 MatDiffuse;\n"
	"    float4 MatAmbient;\n"
	"    float4 MatEmissive;\n"
	"    float4 LightDir[4];\n"
	"    float4 LightDiffuse[4];\n"
	"    uint LightingEnable;\n"
	"    uint NumLights;\n"
	"    uint DiffuseSource;\n"
	"    uint AmbientSource;\n"
	"};\n"
	"#define MAX_BONES 64\n"
	"cbuffer cbSkinning : register(b2)\n"
	"{\n"
	"    row_major float4x4 Bones[MAX_BONES];\n"
	"    uint SkinningEnable;\n"
	"    uint3 _skinpad;\n"
	"    float4 Sway[11];\n"
	"    uint SwayEnable;\n"
	"    uint3 _swaypad;\n"
	"};\n"
	"cbuffer cbTexGen : register(b3)\n"
	"{\n"
	"    row_major float4x4 TexMat[4];\n"
	"    uint4 TexGen[4];\n"
	"};\n"
	"struct VSInput\n"
	"{\n"
	"    float3 pos     : POSITION;\n"
	"    float3 weights : BLENDWEIGHT;\n"
	"    uint4  indices : BLENDINDICES;\n"
	"    float3 normal  : NORMAL;\n"
	"    float4 color   : COLOR0;\n"
	"    float2 uv0     : TEXCOORD0;\n"
	"    float2 uv1     : TEXCOORD1;\n"
	"};\n"
	"struct VSOutput\n"
	"{\n"
	"    float4 pos   : SV_Position;\n"
	"    float4 color : COLOR0;\n"
	"    float2 uv0   : TEXCOORD0;\n"
	"    float2 uv1   : TEXCOORD1;\n"
	"    float  fog   : TEXCOORD2;\n"
	"    float4 gen01 : TEXCOORD3;\n"
	"    float4 gen23 : TEXCOORD4;\n"
	"};\n"
	"VSOutput main(VSInput input)\n"
	"{\n"
	"    VSOutput output;\n"
	"    float4 localPos    = float4(input.pos, 1.0);\n"
	"    float3 localNormal = input.normal;\n"
	"    if (SkinningEnable != 0u) {\n"
	"        float4 w;\n"
	"        w.x = input.weights.x;\n"
	"        w.y = input.weights.y;\n"
	"        w.z = input.weights.z;\n"
	"        w.w = 1.0 - (input.weights.x + input.weights.y + input.weights.z);\n"
	"        float3 blendedPos =\n"
	"            w.x * mul(Bones[input.indices.x], localPos).xyz +\n"
	"            w.y * mul(Bones[input.indices.y], localPos).xyz +\n"
	"            w.z * mul(Bones[input.indices.z], localPos).xyz +\n"
	"            w.w * mul(Bones[input.indices.w], localPos).xyz;\n"
	"        float3 blendedNormal =\n"
	"            w.x * mul((float3x3)Bones[input.indices.x], input.normal) +\n"
	"            w.y * mul((float3x3)Bones[input.indices.y], input.normal) +\n"
	"            w.z * mul((float3x3)Bones[input.indices.z], input.normal) +\n"
	"            w.w * mul((float3x3)Bones[input.indices.w], input.normal);\n"
	"        localPos    = float4(blendedPos, 1.0);\n"
	"        localNormal = blendedNormal;\n"
	"    }\n"
	"    if (SwayEnable != 0u) {\n"
	"        float h = localPos.z - input.normal.z;\n"
	"        localPos.xyz += h * Sway[(uint)input.normal.x].xyz;\n"
	"    }\n"
	"    output.pos = mul(WorldViewProj, localPos);\n"
	"    float4 diffuse = input.color;\n"
	"    if (LightingEnable != 0u) {\n"
	"        float3 N = normalize(mul((float3x3)World, localNormal));\n"
	"        float3 mDiff = (DiffuseSource == 1u) ? input.color.rgb : MatDiffuse.rgb;\n"
	"        float3 mAmb  = (AmbientSource == 1u) ? input.color.rgb : MatAmbient.rgb;\n"
	"        float3 col = MatEmissive.rgb + mAmb * GlobalAmbient.rgb;\n"
	"        [unroll] for (uint i = 0u; i < 4u; ++i) {\n"
	"            if (i < NumLights) {\n"
	"                float3 L = normalize(-LightDir[i].xyz);\n"
	"                float ndl = saturate(dot(N, L));\n"
	"                col += ndl * mDiff * LightDiffuse[i].rgb;\n"
	"            }\n"
	"        }\n"
	"        float a = (DiffuseSource == 1u) ? input.color.a : MatDiffuse.a;\n"
	"        diffuse = float4(saturate(col), a); // D3D8 clamps lit vertex colors before interpolation\n"
	"    }\n"
	"    output.color = diffuse;\n"
	"    output.uv0 = input.uv0;\n"
	"    output.uv1 = input.uv1;\n"
	"    float4 viewPos = mul(View, mul(World, localPos));\n"
	"    output.fog = viewPos.z;\n"
	"    float4 camPos = float4(viewPos.xyz, 1.0);\n"
	"    float2 g0 = float2(0.0, 0.0);\n"
	"    float2 g1 = float2(0.0, 0.0);\n"
	"    float2 g2 = float2(0.0, 0.0);\n"
	"    float2 g3 = float2(0.0, 0.0);\n"
	"    if (TexGen[0].x != 0u) g0 = (TexGen[0].y != 0u) ? mul(camPos, TexMat[0]).xy : camPos.xy;\n"
	"    if (TexGen[1].x != 0u) g1 = (TexGen[1].y != 0u) ? mul(camPos, TexMat[1]).xy : camPos.xy;\n"
	"    if (TexGen[2].x != 0u) g2 = (TexGen[2].y != 0u) ? mul(camPos, TexMat[2]).xy : camPos.xy;\n"
	"    if (TexGen[3].x != 0u) g3 = (TexGen[3].y != 0u) ? mul(camPos, TexMat[3]).xy : camPos.xy;\n"
	"    output.gen01 = float4(g0, g1);\n"
	"    output.gen23 = float4(g2, g3);\n"
	"    return output;\n"
	"}\n";

static const char kFFPixelShaderHLSL[] =
	"cbuffer cbCombiner : register(b0)\n"
	"{\n"
	"    uint gNumStages;\n"
	"    uint3 _pad0;\n"
	"    float4 gTFactor;\n"
	"    uint4 gStageColor[4];\n"
	"    uint4 gStageAlpha[4];\n"
	"    float4 gMonoLum;\n"
	"    float4 gMonoTint;\n"
	"    float4 gMonoFade;\n"
	"    uint gMonoEnable;\n"
	"    uint3 _padm;\n"
	"    uint gAlphaTestEnable;\n"
	"    uint gAlphaTestLE;\n"
	"    float gAlphaTestRef;\n"
	"    uint _padA;\n"
	"};\n"
	"cbuffer cbFog : register(b1)\n"
	"{\n"
	"    float4 FogColor;\n"
	"    uint FogEnable;\n"
	"    uint FogMode;\n"
	"    float FogStart;\n"
	"    float FogEnd;\n"
	"    float FogDensity;\n"
	"    float3 _fogpad;\n"
	"};\n"
	"cbuffer cbTexGen : register(b2)\n"
	"{\n"
	"    row_major float4x4 TexMat[4];\n"
	"    uint4 TexGen[4];\n"
	"};\n"
	"Texture2D gTex0 : register(t0);\n"
	"Texture2D gTex1 : register(t1);\n"
	"Texture2D gTex2 : register(t2);\n"
	"Texture2D gTex3 : register(t3);\n"
	"SamplerState gSmp0 : register(s0);\n"
	"SamplerState gSmp1 : register(s1);\n"
	"SamplerState gSmp2 : register(s2);\n"
	"SamplerState gSmp3 : register(s3);\n"
	"struct PSInput\n"
	"{\n"
	"    float4 pos   : SV_Position;\n"
	"    float4 color : COLOR0;\n"
	"    float2 uv0   : TEXCOORD0;\n"
	"    float2 uv1   : TEXCOORD1;\n"
	"    float  fog   : TEXCOORD2;\n"
	"    float4 gen01 : TEXCOORD3;\n"
	"    float4 gen23 : TEXCOORD4;\n"
	"};\n"
	"#define OP_DISABLE    0\n"
	"#define OP_SELECTARG1 1\n"
	"#define OP_SELECTARG2 2\n"
	"#define OP_MODULATE   3\n"
	"#define OP_MODULATE2X 4\n"
	"#define OP_ADD        5\n"
	"#define ARG_CURRENT 0\n"
	"#define ARG_DIFFUSE 1\n"
	"#define ARG_TEXTURE 2\n"
	"#define ARG_TFACTOR 3\n"
	"#define FOG_NONE   0\n"
	"#define FOG_LINEAR 1\n"
	"#define FOG_EXP    2\n"
	"#define FOG_EXP2   3\n"
	"float4 SampleStage(uint stage, float2 uv)\n"
	"{\n"
	"    switch (stage) {\n"
	"    case 0:  return gTex0.Sample(gSmp0, uv);\n"
	"    case 1:  return gTex1.Sample(gSmp1, uv);\n"
	"    case 2:  return gTex2.Sample(gSmp2, uv);\n"
	"    default: return gTex3.Sample(gSmp3, uv);\n"
	"    }\n"
	"}\n"
	"float3 ResolveColorArg(uint arg, float3 current, float3 texc, float3 diffuse)\n"
	"{\n"
	"    if (arg == ARG_TEXTURE) return texc;\n"
	"    if (arg == ARG_DIFFUSE) return diffuse;\n"
	"    if (arg == ARG_TFACTOR) return gTFactor.rgb;\n"
	"    return current;\n"
	"}\n"
	"float ResolveAlphaArg(uint arg, float current, float texa, float diffuse)\n"
	"{\n"
	"    if (arg == ARG_TEXTURE) return texa;\n"
	"    if (arg == ARG_DIFFUSE) return diffuse;\n"
	"    if (arg == ARG_TFACTOR) return gTFactor.a;\n"
	"    return current;\n"
	"}\n"
	"float3 ApplyColorOp(uint op, float3 a1, float3 a2, float3 current)\n"
	"{\n"
	"    if (op == OP_SELECTARG1) return a1;\n"
	"    if (op == OP_SELECTARG2) return a2;\n"
	"    if (op == OP_MODULATE)   return a1 * a2;\n"
	"    if (op == OP_MODULATE2X) return saturate(a1 * a2 * 2.0);\n"
	"    if (op == OP_ADD)        return saturate(a1 + a2);\n"
	"    return current;\n"
	"}\n"
	"float ApplyAlphaOp(uint op, float a1, float a2, float current)\n"
	"{\n"
	"    if (op == OP_SELECTARG1) return a1;\n"
	"    if (op == OP_SELECTARG2) return a2;\n"
	"    if (op == OP_MODULATE)   return a1 * a2;\n"
	"    if (op == OP_MODULATE2X) return saturate(a1 * a2 * 2.0);\n"
	"    if (op == OP_ADD)        return saturate(a1 + a2);\n"
	"    return current;\n"
	"}\n"
	"float FogFactor(float d)\n"
	"{\n"
	"    if (FogMode == FOG_EXP)  return saturate(1.0 / exp(d * FogDensity));\n"
	"    if (FogMode == FOG_EXP2) return saturate(1.0 / exp((d * FogDensity) * (d * FogDensity)));\n"
	"    return saturate((FogEnd - d) / (FogEnd - FogStart));\n"
	"}\n"
	"float4 main(PSInput input) : SV_Target\n"
	"{\n"
	"    float3 curColor = input.color.rgb;\n"
	"    float  curAlpha = input.color.a;\n"
	"    float2 uvs[2] = { input.uv0, input.uv1 };\n"
	"    // Branch on the live stage count instead of running a uniform dynamic\n"
	"    // loop. gNumStages is uniform per draw, so the GPU takes exactly one path\n"
	"    // and (crucially) skips the sampler+ALU work of the inactive stages. This\n"
	"    // is the hot path for terrain/base tiles (1 stage) and terrain blend/cloud\n"
	"    // passes (2 stages) - several fullscreen draws per frame on iGPUs.\n"
	"    [branch] switch (gNumStages) {\n"
	"    case 0u:\n"
	"        break;\n"
	"    case 1u:\n"
	"    {\n"
	"        uint tci = gStageColor[0].w & 1u;\n"
	"        float2 uv = uvs[tci];\n"
	"        if (TexGen[0].x != 0u) uv = input.gen01.xy;\n"
	"        float4 tex = gTex0.Sample(gSmp0, uv);\n"
	"        float3 c1 = ResolveColorArg(gStageColor[0].y, curColor, tex.rgb, input.color.rgb);\n"
	"        float3 c2 = ResolveColorArg(gStageColor[0].z, curColor, tex.rgb, input.color.rgb);\n"
	"        curColor = ApplyColorOp(gStageColor[0].x, c1, c2, curColor);\n"
	"        float a1 = ResolveAlphaArg(gStageAlpha[0].y, curAlpha, tex.a, input.color.a);\n"
	"        float a2 = ResolveAlphaArg(gStageAlpha[0].z, curAlpha, tex.a, input.color.a);\n"
	"        curAlpha = ApplyAlphaOp(gStageAlpha[0].x, a1, a2, curAlpha);\n"
	"        break;\n"
	"    }\n"
	"    case 2u:\n"
	"    {\n"
	"        uint tci = gStageColor[0].w & 1u;\n"
	"        float2 uv = uvs[tci];\n"
	"        if (TexGen[0].x != 0u) uv = input.gen01.xy;\n"
	"        float4 tex = gTex0.Sample(gSmp0, uv);\n"
	"        float3 c1 = ResolveColorArg(gStageColor[0].y, curColor, tex.rgb, input.color.rgb);\n"
	"        float3 c2 = ResolveColorArg(gStageColor[0].z, curColor, tex.rgb, input.color.rgb);\n"
	"        curColor = ApplyColorOp(gStageColor[0].x, c1, c2, curColor);\n"
	"        float a1 = ResolveAlphaArg(gStageAlpha[0].y, curAlpha, tex.a, input.color.a);\n"
	"        float a2 = ResolveAlphaArg(gStageAlpha[0].z, curAlpha, tex.a, input.color.a);\n"
	"        curAlpha = ApplyAlphaOp(gStageAlpha[0].x, a1, a2, curAlpha);\n"
	"        uint tci2 = gStageColor[1].w & 1u;\n"
	"        float2 uv2 = uvs[tci2];\n"
	"        if (TexGen[1].x != 0u) uv2 = input.gen01.zw;\n"
	"        float4 tex2 = gTex1.Sample(gSmp1, uv2);\n"
	"        float3 d1 = ResolveColorArg(gStageColor[1].y, curColor, tex2.rgb, input.color.rgb);\n"
	"        float3 d2 = ResolveColorArg(gStageColor[1].z, curColor, tex2.rgb, input.color.rgb);\n"
	"        curColor = ApplyColorOp(gStageColor[1].x, d1, d2, curColor);\n"
	"        float b1 = ResolveAlphaArg(gStageAlpha[1].y, curAlpha, tex2.a, input.color.a);\n"
	"        float b2 = ResolveAlphaArg(gStageAlpha[1].z, curAlpha, tex2.a, input.color.a);\n"
	"        curAlpha = ApplyAlphaOp(gStageAlpha[1].x, b1, b2, curAlpha);\n"
	"        break;\n"
	"    }\n"
	"    default:\n"
	"        [unroll] for (uint s = 0; s < 4; ++s) {\n"
	"            if (s < gNumStages) {\n"
	"                uint tci = gStageColor[s].w & 1u;\n"
	"                float2 uv = uvs[tci];\n"
	"                if (TexGen[s].x != 0u) {\n"
	"                    uv = (s == 0u) ? input.gen01.xy\n"
	"                       : (s == 1u) ? input.gen01.zw\n"
	"                       : (s == 2u) ? input.gen23.xy\n"
	"                       :             input.gen23.zw;\n"
	"                }\n"
	"                float4 tex = SampleStage(s, uv);\n"
	"                float3 c1 = ResolveColorArg(gStageColor[s].y, curColor, tex.rgb, input.color.rgb);\n"
	"                float3 c2 = ResolveColorArg(gStageColor[s].z, curColor, tex.rgb, input.color.rgb);\n"
	"                float3 newColor = ApplyColorOp(gStageColor[s].x, c1, c2, curColor);\n"
	"                float a1 = ResolveAlphaArg(gStageAlpha[s].y, curAlpha, tex.a, input.color.a);\n"
	"                float a2 = ResolveAlphaArg(gStageAlpha[s].z, curAlpha, tex.a, input.color.a);\n"
	"                float newAlpha = ApplyAlphaOp(gStageAlpha[s].x, a1, a2, curAlpha);\n"
	"                curColor = newColor;\n"
	"                curAlpha = newAlpha;\n"
	"            }\n"
	"        }\n"
	"        break;\n"
	"    }\n"
	"    if (gMonoEnable != 0u) {\n"
	"        float g = dot(curColor, gMonoLum.rgb);\n"
	"        float4 tinted = g * gMonoTint;\n"
	"        float4 cur4 = lerp(float4(curColor, curAlpha), tinted, gMonoFade);\n"
	"        curColor = cur4.rgb;\n"
	"        curAlpha = cur4.a;\n"
	"    }\n"
	"    if (gAlphaTestEnable != 0u) {\n"
	"        if (gAlphaTestLE != 0u) {\n"
	"            if (curAlpha > gAlphaTestRef) discard;\n"
	"        } else {\n"
	"            if (curAlpha < gAlphaTestRef) discard;\n"
	"        }\n"
	"    }\n"
	"    if (FogEnable != 0u) {\n"
	"        float f = FogFactor(input.fog);\n"
	"        curColor = lerp(FogColor.rgb, curColor, f);\n"
	"    }\n"
	"    return float4(curColor, curAlpha);\n"
	"}\n";

// Clean D3D11 water reflection/surface pixel shader. Replaces the flat FF
// combiner used for lake/trapezoid water on the D3D11 backend with a surface that
// (a) never samples a leaked terrain/unit normal pixel shader (the shimmer root
// cause - see setupFlatWaterShader: terrain+unit PS are restored before water
// draws, so this PS only ever sees its own textures), and (b) gives the water a
// sun-glitter + environment (planar reflection) look.
//
// The U8V8 bump normal map (m_pBumpTexture) is inert on D3D11 (falls back to the
// neutral checker), so wave perturbation + foam + sun glint are driven from the
// water noise texture (t2) sampled with a time-scrolled UV, and the reflection
// (t1) is view-distorted by that same noise in screen space. cbWater (b0) carries
// the water params; cbFog (b1) is SHARED with the FF combiner so water fog matches
// the rest of the scene. Textures/stage setup is done by the caller
// (setupFlatWaterShader): t0 = watermap (river color), t1 = reflection RTT,
// t2 = water noise.
static const char kWaterPixelShaderHLSL[] =
	"cbuffer cbWater : register(b3)\n"
	"{\n"
	"    float4 Params;       // x=BumpScale(wave distort), y=ReflectionFactor, z=SunGlitter, w=Time\n"
	"    float4 ViewportSize; // x=W y=H z=1/W w=1/H\n"
	"    float4 SunDir;\n"
	"    float4 SunColor;\n"
	"};\n"
	"cbuffer cbFog : register(b1)\n"
	"{\n"
	"    float4 FogColor;\n"
	"    uint FogEnable;\n"
	"    uint FogMode;\n"
	"    float FogStart;\n"
	"    float FogEnd;\n"
	"    float FogDensity;\n"
	"    float3 _fogpad;\n"
	"};\n"
	"Texture2D gWaterMap   : register(t0);\n"
	"Texture2D gReflection : register(t1);\n"
	"Texture2D gNoise      : register(t2);\n"
	"SamplerState gSmp0 : register(s0);\n"
	"SamplerState gSmp1 : register(s1);\n"
	"SamplerState gSmp2 : register(s2);\n"
	"struct PSInput\n"
	"{\n"
	"    float4 pos   : SV_Position;\n"
	"    float4 color : COLOR0;\n"
	"    float2 uv0   : TEXCOORD0;\n"
	"    float2 uv1   : TEXCOORD1;\n"
	"    float  fog   : TEXCOORD2;\n"
	"};\n"
	"float FogFactor(float d)\n"
	"{\n"
	"    if (FogMode == 1u) return saturate((FogEnd - d) / (FogEnd - FogStart));\n"
	"    if (FogMode == 2u) return saturate(1.0 / exp(d * FogDensity));\n"
	"    if (FogMode == 3u) return saturate(1.0 / exp((d * FogDensity) * (d * FogDensity)));\n"
	"    return 1.0;\n"
	"}\n"
"float4 main(PSInput input) : SV_Target\n"
"{\n"
"    float t = Params.w * 0.001;\n"
"    float2 nuv = input.uv1;\n"
"    // Shore-directed wave animation: waves travel toward shore (lower V = toward shore)\n"
"    float shoreFactor = 1.0 - saturate(input.uv0.y * 2.0);\n"
"    float shoreWaveSpeed = shoreFactor * 0.5 + 0.5;\n"
"    float2 wave1 = nuv + float2(sin(t * 0.45 * shoreWaveSpeed + nuv.y * 6.0) * 0.35,\n"
"                                cos(t * 0.38 * shoreWaveSpeed + nuv.x * 5.0) * 0.35);\n"
"    float2 wave2 = nuv * 2.3 + float2(sin(t * 0.65 * shoreWaveSpeed + nuv.x * 8.0) * 0.25, 0.0);\n"
"    // Third, finer/faster layer (FBM-style: higher frequency, lower weight)\n"
"    // adds small-scale surface detail on top of the two big swell layers -\n"
"    // real ocean/lake surfaces are a sum of many overlapping wave scales,\n"
"    // not just one or two, so this alone makes the bump pattern read as\n"
"    // much more natural water instead of a simple repeating ripple.\n"
"    float2 wave3 = nuv * 5.3 + float2(cos(t * 0.95 * shoreWaveSpeed + nuv.y * 12.0) * 0.15,\n"
"                                       sin(t * 0.80 * shoreWaveSpeed + nuv.x * 10.0) * 0.15);\n"
"    float4 noise = gNoise.Sample(gSmp2, wave1) * 0.50\n"
"                 + gNoise.Sample(gSmp2, wave2) * 0.32\n"
"                 + gNoise.Sample(gSmp2, wave3) * 0.18;\n"
"    // Increased wave height: Params.x = BumpScale (default ~1.5 -> ~3.0 for taller waves)\n"
"    float2 distort = (noise.rg - 0.5) * 2.0 * saturate(Params.x);\n"
"    float4 base = gWaterMap.Sample(gSmp0, input.uv0) * input.color;\n"
"    float3 waveN = normalize(float3(distort, 1.0));\n"
"    float3 V = normalize(float3(0.0, 0.0, 1.0));\n"
"    float3 L = normalize(SunDir.xyz);\n"
"    float3 R = reflect(-L, waveN);\n"
"    float sunAlign = saturate(dot(R, V));\n"
"    float skyUp = saturate(waveN.z);\n"
"    // The reflection RTT is a planar mirror of the CURRENT screen -\n"
"    // renderMirror() reflects the real camera across the water plane and\n"
"    // renders the scene with it, so the result lines up with normal\n"
"    // screen-space coordinates. It must be sampled with THIS pixel's\n"
"    // screen position, NOT input.uv0: uv0 is the water surface's own\n"
"    // tiling wave-texture coordinate, which repeats many times across a\n"
"    // large lake/ocean. Sampling the RTT with that highly-tiled UV\n"
"    // repeated the same small reflected patch in every tile, producing a\n"
"    // checkerboard grid of tiny reflection blobs instead of one real\n"
"    // reflection - exactly the reported symptom.\n"
"    float2 screenUV = input.pos.xy * ViewportSize.zw;\n"
"    // Offset the sample by the wave bump so the reflection ripples with\n"
"    // the surface instead of looking perfectly flat/static.\n"
"    float2 reflUV = saturate(screenUV + distort * 0.03);\n"
"    float4 refl = gReflection.Sample(gSmp1, reflUV);\n"
"    float3 reflColor = refl.rgb;\n"
"    // Sky reflection component (when no RTT available)\n"
	"    float3 skyRef = lerp(float3(0.10, 0.18, 0.30), float3(0.55, 0.72, 0.90), skyUp);\n"
	"    // Combine real reflection + sky fallback\n"
	"    float hasReflection = (refl.a > 0.01) ? 1.0 : 0.0;\n"
	"    float3 reflFinal = lerp(skyRef, reflColor, hasReflection);\n"
"    // Cap reflection brightness: the mirrored camera can end up staring\n"
"    // almost straight into the sky/sun for a frame or two while the real\n"
"    // camera is rotating, filling the RTT with near-white content. Without\n"
"    // a ceiling that briefly washed the whole water surface out to a flat\n"
"    // milky white. Real water never reflects brighter than a strong but\n"
"    // bounded highlight, so clamp per-channel.\n"
"    reflFinal = min(reflFinal, float3(0.92, 0.92, 0.92));\n"
	"    // Sun glint: a wide specular band so the sun's reflection is actually\n"
	"    // visible on the rippling surface. Two terms: a specular disc (sunAlign)\n"
	"    // for the bright core, plus the wave-crest mask so the glint dances\n"
	"    // across the ripples. Driven mostly by the geometry term (sunAlign) so\n"
	"    // it shows even when the noise texture lacks a blue channel.\n"
	"    // reflFactor/glintFactor must be declared BEFORE first use below -\n"
	"    // using them earlier (as this shader previously did) is a hard HLSL\n"
	"    // compile error (undeclared identifier). That error silently left\n"
	"    // m_waterPixelShader == nullptr forever (see D3D11Backend.cpp), so\n"
	"    // reflection and sun-glint never actually ran on screen.\n"
	"    float reflFactor = saturate(Params.y); // ReflectionFactor\n"
	"    float glintFactor = saturate(Params.z); // SunGlitter\n"
	"    float sunSpec = pow(saturate(sunAlign), 4.0);\n"
	"    float glintMask = pow(saturate(noise.b), 2.0);\n"
	"    float glint = saturate(sunSpec * 1.5 + glintMask * 0.3) * glintFactor;\n"
	"    glint = min(glint, 1.0);\n"
	"    // Combine: base water + reflection + sun glint\n"
	"    float3 col = base.rgb;\n"
	"    // Shallow-to-deep colour grade (bright turquoise near shore fading to\n"
	"    // a deeper blue-teal further out) - the single biggest cue that makes\n"
	"    // water read as a real sea/lake instead of a flat tinted plane. Uses\n"
	"    // the water texture's own alpha (base.a) as the depth proxy - the same\n"
	"    // value already trusted below for the shoreline alpha blend - rather\n"
	"    // than an actual scene-depth buffer, which would need much riskier new\n"
	"    // render-target plumbing (binding the main depth buffer as a shader\n"
	"    // resource while it is also the active depth target elsewhere).\n"
	"    // Applied to the base colour ONLY, before the reflection blend below,\n"
	"    // since the reflection is a surface phenomenon (mirrored sky/objects)\n"
	"    // that should not itself be tinted by water depth.\n"
	"    float depthProxy = smoothstep(0.2, 0.8, base.a);\n"
	"    float3 shallowTint = float3(0.55, 0.95, 0.85);\n"
	"    float3 deepTint = float3(0.10, 0.30, 0.42);\n"
	"    col *= lerp(shallowTint, deepTint, depthProxy);\n"
	"    // Fresnel: real water reflects far more at grazing angles than\n"
	"    // looking straight down (this is the single biggest cue that reads as\n"
	"    // \"natural\" water in modern games). skyUp already equals dot(waveN, V)\n"
	"    // in this shader's local approximation, so reuse it directly - a\n"
	"    // Schlick-style curve boosts reflectivity sharply as skyUp -> 0.\n"
	"    float fresnel = pow(saturate(1.0 - skyUp), 5.0);\n"
	"    // Fresnel strength toned down from an earlier 0.9: combined with a\n"
"    // mirrored camera that can briefly catch bright sky while the real\n"
"    // camera rotates, 0.9 was pushing the water to a flat milky white for\n"
"    // a frame or two. 0.55 still gives a clear grazing-angle brightening\n"
"    // without being able to fully whitewash the surface on its own.\n"
"    float reflAmount = saturate(reflFactor * skyUp + fresnel * 0.55);\n"
	"    col = lerp(col, reflFinal, reflAmount);\n"
	"    col += glint * SunColor.rgb * (0.85 + 0.15 * skyUp);\n"
"    // Soft shoreline alpha from the base water alpha (no extra fetches)\n"
"    float alpha = smoothstep(0.25, 0.75, base.a) * input.color.a;\n"
"    if (FogEnable != 0u)\n"
"    {\n"
"        float f = FogFactor(input.fog);\n"
"        col = lerp(FogColor.rgb, col, f);\n"
"    }\n"
"    return float4(col, alpha);\n"
"}\n";

// Clean D3D11 terrain normal-mapping pixel shader. Replaces the DX8 token-based
// terrain normal shader that D3D11Backend stubs, so terrain gets real HLSL
// normal mapping (no 2n-1 token hacks, no fixed-function BumpEnvMat). Inert
// until the game-side terrain normal feature calls Set_Terrain_Normal_*.
//
// Textures (bound via the existing Set_Texture stage path, t0/t1/t2):
//   gBase  : terrain base/detail color (uv0)
//   gNormal: tangent-space normal atlas, normal in rgb (2n-1 unpacked)
//   gLight : optional baked lightmap (uv1), enabled by TerrainParams.x
// cbTerrain (b0) carries sun direction, sun color, ambient, and flags.
// cbFog (b1) is shared with the FF combiner so fog matches the rest of the scene.
static const char kTerrainNormalPixelShaderHLSL[] =
	"cbuffer cbTerrain : register(b0)\n"
	"{\n"
	"    float4 SunDir;\n"
	"    float4 SunColor;\n"
	"    float4 AmbientColor;\n"
	"    float4 TerrainParams;\n"
	"};\n"
	"cbuffer cbFog : register(b1)\n"
	"{\n"
	"    float4 FogColor;\n"
	"    uint FogEnable;\n"
	"    uint FogMode;\n"
	"    float FogStart;\n"
	"    float FogEnd;\n"
	"    float FogDensity;\n"
	"    float3 _fogpad;\n"
	"};\n"
	"Texture2D gBase  : register(t0);\n"
	"Texture2D gNormal : register(t1);\n"
	"Texture2D gLight : register(t2);\n"
	"SamplerState gSmp0 : register(s0);\n"
	"SamplerState gSmp1 : register(s1);\n"
	"SamplerState gSmp2 : register(s2);\n"
	"struct PSInput\n"
	"{\n"
	"    float4 pos   : SV_Position;\n"
	"    float4 color : COLOR0;\n"
	"    float2 uv0   : TEXCOORD0;\n"
	"    float2 uv1   : TEXCOORD1;\n"
	"    float  fog   : TEXCOORD2;\n"
	"    float4 gen01 : TEXCOORD3;\n"
	"    float4 gen23 : TEXCOORD4;\n"
	"};\n"
	"float FogFactor(float d)\n"
	"{\n"
	"    if (FogMode == 1u) return saturate((FogEnd - d) / (FogEnd - FogStart));\n"
	"    if (FogMode == 2u) return saturate(1.0 / exp(d * FogDensity));\n"
	"    if (FogMode == 3u) return saturate(1.0 / exp((d * FogDensity) * (d * FogDensity)));\n"
	"    return 1.0;\n"
	"}\n"
	"float4 main(PSInput input) : SV_Target\n"
	"{\n"
	"    float2 uv0c = clamp(input.uv0, 0.0, 1.0);\n"
	"    float2 uv1c = clamp(input.uv1, 0.0, 1.0);\n"
	"    // Crossfade base colour AND normal map across texture boundaries using the\n"
	"    // per-vertex blend weight (input.color.a) - the same mechanism the base\n"
	"    // colour pass uses. For non-blend tiles the weight is 0, so this reduces to\n"
	"    // the own tile (relief preserved). For border tiles it smoothly blends\n"
	"    // own<->neighbour, removing the jagged/mosaic normal edges.\n"
	"    float blend = input.color.a;\n"
	"    if (blend > 1.001) blend /= 255.0;   // tolerate 0-255 vs 0-1 vertex colour\n"
	"    blend = saturate(blend);\n"
	"    float4 baseOwn = gBase.Sample(gSmp0, uv0c);\n"
	"    float4 nrmOwn = gNormal.Sample(gSmp1, uv0c);\n"
	"    float3 baseRGB = baseOwn.rgb;\n"
	"    float3 nrm3O = nrmOwn.xyz * 2.0 - 1.0;\n"
	"    float nrmLenO = dot(nrm3O, nrm3O);\n"
	"    float3 N = (nrmLenO < 1e-6) ? float3(0.0, 0.0, 1.0) : normalize(float3(nrm3O.xy * 0.85f, nrm3O.z)); float3 NF = (nrmLenO < 1e-6) ? float3(0.0, 0.0, 1.0) : nrm3O * rsqrt(nrmLenO);\n"
	"    // Only pay for the neighbour (uv1) samples on actual border tiles. The\n"
	"    // vast majority of terrain tiles have blend==0, so this keeps the pass\n"
	"    // at the original 2-sample cost for them (no FPS regression from the\n"
	"    // edge-blend feature). Use SampleLevel to avoid derivative-in-branch issues.\n"
	"    // Match the neighbour samples' mip level to the own-tile auto LOD:\n"
	"    // sampling the neighbour at fixed LOD 0 made the two textures shimmer\n"
	"    // against each other along the blend lines as distance changed.\n"
	"    float blendLod = gNormal.CalculateLevelOfDetail(gSmp1, uv0c);\n"
	"    [branch] if (blend > 0.0)\n"
	"    {\n"
	"        float4 baseNbr = gBase.SampleLevel(gSmp0, uv1c, blendLod);\n"
	"        float4 nrmNbr = gNormal.SampleLevel(gSmp1, uv1c, blendLod);\n"
	"        float3 nrm3N = nrmNbr.xyz * 2.0 - 1.0;\n"
	"        float nrmLenN = dot(nrm3N, nrm3N);\n"
	"        float3 NN = (nrmLenN < 1e-6) ? float3(0.0, 0.0, 1.0) : normalize(float3(nrm3N.xy * 0.85f, nrm3N.z)); float3 NNF = (nrmLenN < 1e-6) ? float3(0.0, 0.0, 1.0) : nrm3N * rsqrt(nrmLenN);\n"
	"        baseRGB = lerp(baseOwn.rgb, baseNbr.rgb, blend);\n"
	"        N = normalize(lerp(N, NN, blend)); NF = normalize(lerp(NF, NNF, blend));\n"
	"    }\n"
	"    float3 L = normalize(SunDir.xyz);\n"
	"    float ndl = saturate(dot(N, L));\n"
	"    // Preserve the prelit (baked) vertex diffuse - the original DX8 terrain\n"
	"    // path multiplies base x vertexDiffuse (lightmap shadows, slope shading and\n"
	"    // day/night tint are all baked into the vertex colour at map load).\n"
	"    // Replacing it with live ambient/sun constants threw that baked lighting\n"
	"    // away and made the terrain read as dirty/flat. The normal map RELIEF\n"
	"    // modulates the directional term only: flat normals (N=(0,0,1)) give\n"
	"    // relief == 1, so flat texels stay pixel-identical to the 2-stage FF look\n"
	"    // while bumped texels brighten toward the sun and darken away from it.\n"
	"    float3 vd = saturate(input.color.rgb);\n"
	"    float dFlat = max(saturate(L.z), 0.15f);\n"
	"    float relief = clamp(ndl / dFlat, 0.4f, 2.0f);\n"
	"    float3 litRGB = vd * relief;\n"
	"    float sunL = (SunColor.r + SunColor.g + SunColor.b) * 0.3333;\n"
	"    float3 col = baseRGB * litRGB; { float steep = saturate(length(N.xy) * 2.0); col *= 1.0 - steep * TerrainParams.z * saturate(L.z); float3 Hv = normalize(L + float3(0.0, 0.0, 1.0)); float spec = pow(saturate(dot(N, Hv)), max(TerrainParams.w, 1.0)) * TerrainParams.y; col += spec * sunL; }\n"
	"    if (TerrainParams.x > 0.5)\n"
	"    {\n"
	"        float4 lm = gLight.Sample(gSmp2, input.gen23.xy);\n"
	"        float lmL = (lm.r + lm.g + lm.b) * 0.3333;\n"
	"        col *= lmL;\n"
	"    }\n"
	"    if (FogEnable != 0u)\n"
	"    {\n"
	"        float f = FogFactor(input.fog);\n"
	"        col = lerp(FogColor.rgb, col, f);\n"
	"    }\n"
	"    return float4(col, baseOwn.a);\n"
	"}\n";

// Terrain normal-mapping BLEND variant. Used by the separate
// renderNormalEdgeBlend() pass to crossfade the normal map (and base colour)
// across texture boundaries, exactly like the base colour pass, but outputting
// the per-vertex blend weight (input.color.a) as the pixel alpha so the tile
// smoothly blends with the opaque main terrain pass underneath. getAlphaUVData
// supplies the per-corner 0/255 blend weight (no hand-made feather).
static const char kTerrainNormalBlendPixelShaderHLSL[] =
	"cbuffer cbTerrain : register(b0)\n"
	"{\n"
	"    float4 SunDir;\n"
	"    float4 SunColor;\n"
	"    float4 AmbientColor;\n"
	"    float4 TerrainParams;\n"
	"};\n"
	"cbuffer cbFog : register(b1)\n"
	"{\n"
	"    float4 FogColor;\n"
	"    uint FogEnable;\n"
	"    uint FogMode;\n"
	"    float FogStart;\n"
	"    float FogEnd;\n"
	"    float FogDensity;\n"
	"    float3 _fogpad;\n"
	"};\n"
	"Texture2D gBase  : register(t0);\n"
	"Texture2D gNormal : register(t1);\n"
	"Texture2D gLight : register(t2);\n"
	"SamplerState gSmp0 : register(s0);\n"
	"SamplerState gSmp1 : register(s1);\n"
	"SamplerState gSmp2 : register(s2);\n"
	"struct PSInput\n"
	"{\n"
	"    float4 pos   : SV_Position;\n"
	"    float4 color : COLOR0;\n"
	"    float2 uv0   : TEXCOORD0;\n"
	"    float2 uv1   : TEXCOORD1;\n"
	"    float  fog   : TEXCOORD2;\n"
	"    float4 gen01 : TEXCOORD3;\n"
	"    float4 gen23 : TEXCOORD4;\n"
	"};\n"
	"float FogFactor(float d)\n"
	"{\n"
	"    if (FogMode == 1u) return saturate((FogEnd - d) / (FogEnd - FogStart));\n"
	"    if (FogMode == 2u) return saturate(1.0 / exp(d * FogDensity));\n"
	"    if (FogMode == 3u) return saturate(1.0 / exp((d * FogDensity) * (d * FogDensity)));\n"
	"    return 1.0;\n"
	"}\n"
	"float4 main(PSInput input) : SV_Target\n"
	"{\n"
	"    float2 uv1c = clamp(input.uv1, 0.0, 1.0);\n"
	"    // The blend pass overlays the NEIGHBOUR terrain (sampled at uv1, the\n"
	"    // neighbour atlas UV from getAlphaUVData) on top of the opaque main pass,\n"
	"    // which already drew the OWN terrain. The per-vertex blend weight\n"
	"    // (input.color.a) is the pixel alpha, so the rasteriser crossfades\n"
	"    // own<->neighbour across the cell (no hand-made feather).\n"
	"    float4 baseNbr = gBase.Sample(gSmp0, uv1c);\n"
	"    float4 nrmNbr  = gNormal.Sample(gSmp1, uv1c);\n"
	"    float3 nrm3 = nrmNbr.xyz * 2.0 - 1.0;\n"
	"    float nrmLenSq = dot(nrm3, nrm3);\n"
	"    float3 N = (nrmLenSq < 1e-6) ? float3(0.0, 0.0, 1.0) : normalize(float3(nrm3.xy * 0.5f, nrm3.z));\n"
	"    float3 L = normalize(SunDir.xyz);\n"
	"    float ndl = saturate(dot(N, L));\n"
	"    // Preserve the baked vertex diffuse + normal-map relief - see the main\n"
	"    // terrain shader. Must match the main pass exactly or the blend crossfade\n"
	"    // between them would visibly shift colour along the seam.\n"
	"    float3 vd = saturate(input.color.rgb);\n"
	"    float dFlat = max(saturate(L.z), 0.15f);\n"
	"    float relief = clamp(ndl / dFlat, 0.4f, 2.0f);\n"
	"    float3 litRGB = vd * relief;\n"
	"    float3 col = baseNbr.rgb * litRGB;\n"
	"    // Output neighbour lit colour with the blend weight as alpha. The blend\n"
	"    // equation (SRC=ALPHA, DST=INVALPHA) crossfades over the main pass.\n"
	"    return float4(col, input.color.a);\n"
	"}\n";

// W3DNext color-grading post-process. Self-contained full-screen pair run at
// End_Frame just before Present: the finished frame is copied into an off-
// screen texture and redrawn through this pair with brightness / contrast /
// saturation / tint applied. Neutral when GradeParams=(1,1,1) and
// GradeTint=(1,1,1). The vertex stage builds a fullscreen quad from
// SV_VertexID so no vertex buffer or input layout is needed.
static const char kColorGradeVertexShaderHLSL[] =
	"struct GsOut\n"
	"{\n"
	"    float4 pos : SV_Position;\n"
	"    float2 uv  : TEXCOORD0;\n"
	"};\n"
	"GsOut main(uint id : SV_VertexID)\n"
	"{\n"
	"    GsOut o;\n"
	"    float2 uv = float2(float((id << 1u) & 2u), float(id & 2u));\n"
	"    o.uv = uv;\n"
	"    o.pos = float4(uv.x * 2.0 - 1.0, 1.0 - uv.y * 2.0, 0.0, 1.0);\n"
	"    return o;\n"
	"}\n";

static const char kColorGradePixelShaderHLSL[] =
"cbuffer cbGrade : register(b0)\n"
"{\n"
"    float4 GradeParams; // x brightness, y contrast, z saturation, w time (dust drift)\n"
"    float4 GradeTint;   // rgb balance multiplier, a unused\n"
"    float4 GradeMode;   // x = night-vision enable, y = god rays, z = filmic+bloom enable\n"
"    float4 Sun;         // xy = sun screen uv, z = ray intensity (0 = off)\n"
"    float4 GradeBloom;  // x = exposure, y = bloom strength, z = bloom threshold, w = bloom radius(px)\n"
"};\n"
	"Texture2D gScene : register(t0);\n"
	"SamplerState gSmpG : register(s0);\n"
	"// GPU Gems 3 ch.13 style radial scattering + open-standard FBM dust:\n"
	"// light shafts only become visible where the drifting dust density field\n"
	"// scatters them (wind-scrolling value noise, two octaves).\n"
	"float GradeVNoise(float2 p)\n"
	"{\n"
	"    float2 i = floor(p);\n"
	"    float2 f = frac(p);\n"
	"    f = f * f * (3.0 - 2.0 * f);\n"
	"    float a = frac(sin(dot(i, float2(127.1, 311.7))) * 43758.5453);\n"
	"    float b = frac(sin(dot(i + float2(1, 0), float2(127.1, 311.7))) * 43758.5453);\n"
	"    float c = frac(sin(dot(i + float2(0, 1), float2(127.1, 311.7))) * 43758.5453);\n"
	"    float d = frac(sin(dot(i + float2(1, 1), float2(127.1, 311.7))) * 43758.5453);\n"
	"    return lerp(lerp(a, b, f.x), lerp(c, d, f.x), f.y);\n"
	"}\n"
	"float GradeDust(float2 p, float t)\n"
	"{\n"
	"    float2 q = p * 7.0 + float2(t * 0.06, -t * 0.04);\n"
	"    float n = GradeVNoise(q) * 0.62 + GradeVNoise(q * 2.7 + float2(t * 0.13, 0.0)) * 0.38;\n"
"    return saturate(n * 1.2 - 0.42);\n"
"}\n"
"// Filmic ACES (Narkowicz 2015) tone mapping - the 'modern game' look: rolls\n"
"// off blown highlights and enriches mid tones. Fed the 0..1 scene copy it\n"
"// acts as a gentle filmic grade; with true HDR input it is a straight ACES.\n"
"float3 GradeFilmicACES(float3 x)\n"
"{\n"
"    return saturate(x * (2.51 * x + 0.03) / (x * (2.43 * x + 0.59) + 0.14));\n"
"}\n"
"// Single-pass cheap bloom: bright-pass the scene, then gather a soft\n"
"// gaussian halo over two expanding rings (16 taps) and add it behind the\n"
"// tonemap. 'radius' is in texels; the one-pixel texel vector comes from\n"
"// GetDimensions in main.\n"
"float3 GradeBloomGather(float2 uv, float2 texel, float radius, float threshold)\n"
"{\n"
"    float3 acc = float3(0.0, 0.0, 0.0);\n"
"    float wsum = 0.0;\n"
"    const float2 kDir0 = float2(1.0, 0.0);\n"
"    const float2 kDir1 = float2(0.7071, 0.7071);\n"
"    const float2 kDir2 = float2(0.0, 1.0);\n"
"    const float2 kDir3 = float2(-0.7071, 0.7071);\n"
"    const float2 kDir4 = float2(-1.0, 0.0);\n"
"    const float2 kDir5 = float2(-0.7071, -0.7071);\n"
"    const float2 kDir6 = float2(0.0, -1.0);\n"
"    const float2 kDir7 = float2(0.7071, -0.7071);\n"
"    const float2 kDir[8] = { kDir0, kDir1, kDir2, kDir3, kDir4, kDir5, kDir6, kDir7 };\n"
"    const float kRad[2] = { 1.2, 3.2 };\n"
"    const float kWgt[2] = { 0.55, 0.45 };\n"
"    [unroll] for (int r = 0; r < 2; ++r)\n"
"    {\n"
"        [unroll] for (int d = 0; d < 8; ++d)\n"
"        {\n"
"            float2 off = kDir[d] * (kRad[r] * radius) * texel;\n"
"            float3 s = gScene.Sample(gSmpG, uv + off).rgb;\n"
"            float br = max(max(s.r, s.g), s.b);\n"
"            float b = saturate((br - threshold) / max(1.0 - threshold, 1e-4));\n"
"            acc += b * b * kWgt[r] * s;\n"
"            wsum += kWgt[r];\n"
"        }\n"
"    }\n"
"    return (wsum > 0.0) ? acc / wsum : acc;\n"
"}\n"
"struct GsOut { float4 pos : SV_Position; float2 uv : TEXCOORD0; };\n"
"float4 main(GsOut input) : SV_Target\n"
"{\n"
"    float3 c = gScene.Sample(gSmpG, input.uv).rgb;\n"
"    // Exposure first, then filmic tone-map + bloom, then the classic\n"
"    // brightness / contrast / saturation / tint grade on top. With the new\n"
"    // effect disabled (GradeMode.z = 0) and exposure 1.0 this is bit-identical\n"
"    // to the old path.\n"
"    c *= GradeBloom.x;\n"
"    if (GradeMode.z > 0.5)\n"
"    {\n"
"        if (GradeBloom.y > 0.001)\n"
"        {\n"
"            float2 texel;\n"
"            gScene.GetDimensions(texel.x, texel.y);\n"
"            texel = float2(1.0, 1.0) / texel;\n"
"            c += GradeBloomGather(input.uv, texel, GradeBloom.w, GradeBloom.z) * GradeBloom.y;\n"
"        }\n"
"        c = GradeFilmicACES(c);\n"
"    }\n"
"    c *= GradeParams.x;\n"
"    c = (c - 0.5) * GradeParams.y + 0.5;\n"
	"    float l = dot(c, float3(0.299, 0.587, 0.114));\n"
	"    c = lerp(l.xxx, c, GradeParams.z);\n"
	"    c *= GradeTint.rgb;\n"
	"    // Night-vision (grade green pass) - GradeMode.x (F6). Converts the\n"
	"    // graded frame to a single luminance channel, re-exposes it for\n"
	"    // darkness (generic midtones get lifted while bright sources stay\n"
	"    // blown), pushes contrast so silhouettes read clearly, then paints it\n"
	"    // in a phosphor green with a timed sparkle-noise grain and a soft\n"
	"    // vignette (screen-edge falloff that mimics real NV optics). With\n"
	"    // GradeMode.x = 0 this branch is a no-op and output is unchanged.\n"
	"    if (GradeMode.x > 0.5)\n"
	"    {\n"
	"        float nvL = dot(c, float3(0.299, 0.587, 0.114));\n"
	"        nvL = (nvL * 0.9 + 0.10) * 1.35;              // night-lift then contrast\n"
	"        nvL = (nvL - 0.5) * 1.18 + 0.5;\n"
	"        float nvT = GradeParams.w;\n"
	"        float nvA = frac(sin(dot(input.uv * 423.1 + nvT * 7.0, float2(12.9898, 78.233))) * 43758.5453);\n"
	"        float nvB = frac(sin(dot(input.uv * 391.7 - nvT * 5.0, float2(263.5, 126.9))) * 24634.6345);\n"
	"        c = float3(nvL * 0.23, nvL * 0.72, nvL * 0.26);   // phosphor green\n"
	"        c += float3(0.015, 0.045, 0.017) * (nvA + nvB);    // sensor grain\n"
	"        float2 nvV = input.uv - 0.5;\n"
	"        c *= 1.0 - saturate(dot(nvV, nvV) * 1.6) * 0.35;   // NV vignette\n"
	"        c = saturate(c);\n"
	"    }\n"
	"    if (GradeMode.y > 0.5 && Sun.z > 0.001)\n"
	"    {\n"
	"        // Dust-mote god rays: march from this pixel toward the sun's\n"
	"        // screen position and treat sufficiently bright samples as\n"
	"        // scattering dust. Two changes vs the original version, which\n"
	"        // made ordinary bright surfaces (white unit paint, sunlit walls,\n"
	"        // chrome) look like they were emitting their own light:\n"
	"        //   1) the brightness gate is reshaped (pow curve, higher floor)\n"
	"        //      so only near-blown-out pixels (true sun/sky) qualify -\n"
	"        //      an ordinary lit surface no longer registers as a source;\n"
	"        //   2) the first few samples nearest THIS pixel are skipped (a\n"
	"        //      minimum march distance), so a bright surface can no\n"
	"        //      longer light up its own immediate neighbourhood;\n"
	"        //   3) the whole effect fades with on-screen distance to the\n"
	"        //      sun anchor, so rays stay concentrated near the sun/sky\n"
	"        //      instead of hazing the entire frame uniformly.\n"
	"        float t = GradeParams.w;\n"
	"        float g1 = frac(sin(dot(input.uv * 913.7 + t, float2(12.9898, 78.233))) * 43758.5453);\n"
	"        float dust = GradeDust(input.uv, t);\n"
	"        float2 toSun = Sun.xy - input.uv;\n"
	"        float distToSun = length(toSun);\n"
	"        float2 dir = toSun * (0.35 / 18.0);\n"
	"        float2 suv = input.uv + dir * g1;\n"
	"        float acc = 0.0;\n"
	"        float w = 1.0;\n"
	"        float wsum = 0.0;\n"
	"        [unroll] for (int i = 0; i < 18; ++i)\n"
	"        {\n"
	"            suv += dir;\n"
	"            float3 s = gScene.Sample(gSmpG, suv).rgb;\n"
	"            float l = max(max(s.r, s.g), s.b);\n"
	"            // Per-sample jitter: spreads each sample into a soft disc so\n"
	"            // bright objects smear into glow instead of thin strings that\n"
	"            // appear wired to the sun anchor.\n"
	"            float j1 = frac(sin(dot(suv * 731.3 + t * 3.1, float2(269.5, 183.3))) * 43758.5453);\n"
	"            float j2 = frac(sin(dot(suv * 517.7 - t * 2.3, float2(101.7, 291.1))) * 24634.6345);\n"
	"            float2 jOff = float2(j1 - 0.5, j2 - 0.5) * 0.014;\n"
	"            float3 sj = gScene.Sample(gSmpG, suv + jOff).rgb;\n"
	"            float lj = max(max(sj.r, sj.g), sj.b);\n"
	"            l = max(l, lj);\n"
	"            float ws = (0.35 + 0.9 * dust) * w;\n"
	"            // Reshaped gate: only near-1.0 (true sun/sky/blown highlight)\n"
	"            // samples pass meaningfully now - an ordinary lit surface\n"
	"            // (l roughly 0.6-0.85) contributes almost nothing.\n"
	"            float gate = (i < 5) ? 0.0 : pow(saturate((l - 0.78) / 0.22), 6.0);\n"
	"            acc += gate * ws;\n"
	"            wsum += ws;\n"
	"            w *= 0.86;\n"
	"        }\n"
	"        acc /= wsum;\n"
	"        float g2 = frac(sin(dot(input.uv * 573.9 - t * 2.7, float2(419.2, 371.9))) * 24634.6345);\n"
	"        // Fade with on-screen distance to the sun so shafts stay near\n"
	"        // the sun/sky instead of glowing every bright surface on screen.\n"
	"        // Tightened falloff (1.35 -> 2.6) and lower overall strength\n"
	"        // (3.6 -> 1.7): a wide bright sky region (e.g. an overcast shell-\n"
	"        // map background) could still trigger a big washed-out halo\n"
	"        // across most of the screen even with the smooth sun-tracking\n"
	"        // fix, since many pixels legitimately have a bright sky sample\n"
	"        // along their march path toward the sun at once. This keeps the\n"
	"        // effect a subtle shaft near the sun instead of a broad glow.\n"
	"        float sunFalloff = saturate(1.0 - distToSun * 2.6);\n"
	"        c += acc * (0.55 + 0.7 * g2) * 1.7 * (0.3 + 0.7 * dust) * Sun.z * sunFalloff * float3(1.0, 0.9, 0.74);\n"
	"    }\n"
	"    return float4(saturate(c), 1.0);\n"
	"}\n";

// Clean D3D11 unit/model normal-mapping path (mirrors the terrain normal
// path). Units and props are drawn with the shared FF pipeline (per-vertex
// Lambert) unless the game-side unit normal feature switches them to this
// pair. The vertex shader forwards world position + world normal so the pixel
// shader can build a tangent basis from screen-space derivatives (no vertex
// tangents needed) and do per-pixel Blinn-Phong lighting with an optional
// tangent-space normal map.
static const char kUnitNormalVertexShaderHLSL[] =
	"cbuffer cbPerObject : register(b0)\n"
	"{\n"
	"    row_major float4x4 WorldViewProj;\n"
	"};\n"
	"cbuffer cbLighting : register(b1)\n"
	"{\n"
	"    row_major float4x4 World;\n"
	"    row_major float4x4 View;\n"
	"    float4 GlobalAmbient;\n"
	"    float4 MatDiffuse;\n"
	"    float4 MatAmbient;\n"
	"    float4 MatEmissive;\n"
	"    float4 LightDir[4];\n"
	"    float4 LightDiffuse[4];\n"
	"    uint LightingEnable;\n"
	"    uint NumLights;\n"
	"    uint DiffuseSource;\n"
	"    uint AmbientSource;\n"
	"};\n"
	"#define MAX_BONES 64\n"
	"cbuffer cbSkinning : register(b2)\n"
	"{\n"
	"    row_major float4x4 Bones[MAX_BONES];\n"
	"    uint SkinningEnable;\n"
	"    uint3 _skinpad;\n"
	"    float4 Sway[11];\n"
	"    uint SwayEnable;\n"
	"    uint3 _swaypad;\n"
	"};\n"
	"struct VSInput\n"
	"{\n"
	"    float3 pos : POSITION;\n"
	"    float3 weights : BLENDWEIGHT;\n"
	"    uint4 indices : BLENDINDICES;\n"
	"    float3 normal : NORMAL;\n"
	"    float4 color : COLOR0;\n"
	"    float2 uv0 : TEXCOORD0;\n"
	"    float2 uv1 : TEXCOORD1;\n"
	"};\n"
	"struct VSOutput\n"
	"{\n"
	"    float4 pos : SV_Position;\n"
	"    float3 worldPos : TEXCOORD0;\n"
	"    float3 worldNormal : TEXCOORD1;\n"
	"    float2 uv0 : TEXCOORD2;\n"
	"    float4 color : COLOR0;\n"
	"    float fog : TEXCOORD3;\n"
	"};\n"
	"VSOutput main(VSInput input)\n"
	"{\n"
	"    VSOutput output;\n"
	"    float4 localPos = float4(input.pos, 1.0);\n"
	"    float3 localNormal = input.normal;\n"
	"    if (SkinningEnable != 0u) {\n"
	"        float4 w;\n"
	"        w.x = input.weights.x;\n"
	"        w.y = input.weights.y;\n"
	"        w.z = input.weights.z;\n"
	"        w.w = 1.0 - (input.weights.x + input.weights.y + input.weights.z);\n"
	"        float3 bp =\n"
	"            w.x * mul(Bones[input.indices.x], localPos).xyz +\n"
	"            w.y * mul(Bones[input.indices.y], localPos).xyz +\n"
	"            w.z * mul(Bones[input.indices.z], localPos).xyz +\n"
	"            w.w * mul(Bones[input.indices.w], localPos).xyz;\n"
	"        float3 bn =\n"
	"            w.x * mul((float3x3)Bones[input.indices.x], input.normal) +\n"
	"            w.y * mul((float3x3)Bones[input.indices.y], input.normal) +\n"
	"            w.z * mul((float3x3)Bones[input.indices.z], input.normal) +\n"
	"            w.w * mul((float3x3)Bones[input.indices.w], input.normal);\n"
	"        localPos = float4(bp, 1.0);\n"
	"        localNormal = bn;\n"
	"    }\n"
	"    if (SwayEnable != 0u) {\n"
	"        float h = localPos.z - input.normal.z;\n"
	"        localPos.xyz += h * Sway[(uint)input.normal.x].xyz;\n"
	"    }\n"
	"    float4 wp = mul(World, localPos);\n"
	"    output.worldPos = wp.xyz;\n"
	"    output.pos = mul(WorldViewProj, localPos);\n"
    "    float3 Nw = normalize(mul((float3x3)World, localNormal));\n"
    "    output.worldNormal = Nw;\n"
    "    output.uv0 = input.uv0;\n"
    "    float4 litColor = input.color;\n"
    "    if (LightingEnable != 0u) {\n"
    "        float3 mDiff = (DiffuseSource == 1u) ? input.color.rgb : MatDiffuse.rgb;\n"
    "        float3 mAmb  = (AmbientSource == 1u) ? input.color.rgb : MatAmbient.rgb;\n"
    "        float3 col = MatEmissive.rgb + mAmb * GlobalAmbient.rgb;\n"
    "        [unroll] for (uint i = 0u; i < 4u; ++i) {\n"
    "            if (i < NumLights) {\n"
    "                float3 L = normalize(-LightDir[i].xyz);\n"
    "                float ndl = saturate(dot(Nw, L));\n"
    "                col += ndl * mDiff * LightDiffuse[i].rgb;\n"
    "            }\n"
    "        }\n"
    "        float a = (DiffuseSource == 1u) ? input.color.a : MatDiffuse.a;\n"
    "        litColor = float4(saturate(col), a);\n"
    "    }\n"
    "    output.color = litColor;\n"
	"    float4 vp = mul(View, wp);\n"
	"    output.fog = vp.z;\n"
	"    return output;\n"
	"}\n";

static const char kUnitNormalPixelShaderHLSL[] =
	"cbuffer cbUnit : register(b0)\n"
	"{\n"
	"    float4 SunDir;\n"
	"    float4 SunColor;\n"
	"    float4 AmbientColor;\n"
	"    float4 CameraPos;\n"
	"    float4 SpecularColor;\n"
	"    float4 Params;   // x=specPower, y=normalIntensity, z=enableSpec, w=enableNormal\n"
	"    float4 MatTint;\n"
	"    float4 Params2;  // x=metalness, y=roughness, z=envStrength, w=enablePBR\n"
	"    float4 Alpha;    // x=alphaTestEnable, y=alphaTestLessEqual, z=alphaTestRef\n"
	"};\n"
	"cbuffer cbFog : register(b1)\n"
	"{\n"
	"    float4 FogColor;\n"
	"    uint FogEnable;\n"
	"    uint FogMode;\n"
	"    float FogStart;\n"
	"    float FogEnd;\n"
	"    float FogDensity;\n"
	"    float3 _fogpad;\n"
	"};\n"
	"Texture2D gBase : register(t0);\n"
	"Texture2D gNormal : register(t1);\n"
	"SamplerState gSmp0 : register(s0);\n"
	"SamplerState gSmp1 : register(s1);\n"
	"struct PSInput\n"
	"{\n"
	"    float4 pos : SV_Position;\n"
	"    float3 worldPos : TEXCOORD0;\n"
	"    float3 worldNormal : TEXCOORD1;\n"
	"    float2 uv0 : TEXCOORD2;\n"
	"    float4 color : COLOR0;\n"
	"    float fog : TEXCOORD3;\n"
	"};\n"
	"float FogFactor(float d)\n"
	"{\n"
	"    if (FogMode == 1u) return saturate((FogEnd - d) / (FogEnd - FogStart));\n"
	"    if (FogMode == 2u) return saturate(1.0 / exp(d * FogDensity));\n"
	"    if (FogMode == 3u) return saturate(1.0 / exp((d * FogDensity) * (d * FogDensity)));\n"
	"    return 1.0;\n"
	"}\n"
	"// Procedural sky/environment approximation for metal reflections.\n"
	"// No cube map needed: synthesize a simple sky gradient from the view\n"
	"// direction, giving metal surfaces a believable environment reflection.\n"
	"float3 EnvSample(float3 dir)\n"
	"{\n"
	"    float up = saturate(dir.z * 0.5 + 0.5);\n"
	"    float3 sky = lerp(float3(0.25, 0.35, 0.55), float3(0.55, 0.65, 0.80), up);\n"
	"    float3 ground = float3(0.15, 0.12, 0.10);\n"
	"    float grnd = saturate(-dir.z * 0.5 + 0.5);\n"
	"    return lerp(sky, ground, grnd * 0.5);\n"
	"}\n"
	"float3 FresnelSchlick(float cosTheta, float3 F0)\n"
	"{\n"
	"    return F0 + (1.0 - F0) * pow(1.0 - cosTheta, 5.0);\n"
	"}\n"
	"float DistributionGGX(float3 N, float3 H, float roughness)\n"
	"{\n"
	"    float a = roughness * roughness;\n"
	"    float a2 = a * a;\n"
	"    float NdotH = saturate(dot(N, H));\n"
	"    float NdotH2 = NdotH * NdotH;\n"
	"    float denom = NdotH2 * (a2 - 1.0) + 1.0;\n"
	"    denom = 3.14159 * denom * denom;\n"
	"    return a2 / max(denom, 1e-4);\n"
	"}\n"
	"float GeometrySmith(float3 N, float3 V, float3 L, float roughness)\n"
	"{\n"
	"    float r = roughness + 1.0;\n"
	"    float k = (r * r) / 8.0;\n"
	"    float NdotV = saturate(dot(N, V));\n"
	"    float NdotL = saturate(dot(N, L));\n"
	"    float gv = NdotV * (1.0 - k) + k;\n"
	"    float gl = NdotL * (1.0 - k) + k;\n"
	"    return (gv * gl) / max(NdotV * NdotL, 1e-4);\n"
	"}\n"
	"float4 main(PSInput input) : SV_Target\n"
	"{\n"
	"    float4 base = gBase.Sample(gSmp0, input.uv0);\n"
	"    float3 vtxLit = base.rgb * MatTint.rgb * input.color.rgb;\n"
	"    float3 N = input.worldNormal;\n"
	"    if (dot(N, N) < 1e-8) { N = float3(0.0, 0.0, 1.0); } else { N = normalize(N); }\n"
	"    // Build TBN from screen-space derivatives (standard technique).\n"
	"    if (Params.w > 0.5) {\n"
	"        float3 dpdx = ddx(input.worldPos);\n"
	"        float3 dpdy = ddy(input.worldPos);\n"
	"        float2 duvdx = ddx(input.uv0);\n"
	"        float2 duvdy = ddy(input.uv0);\n"
	"        float det = duvdx.x * duvdy.y - duvdx.y * duvdy.x;\n"
	"        float3 T, Bt;\n"
	"        if (abs(det) > 1e-6) {\n"
	"            float invDet = 1.0 / det;\n"
	"            T  = normalize((dpdx * duvdy.y - dpdy * duvdx.y) * invDet);\n"
	"            Bt = normalize((dpdy * duvdx.x - dpdx * duvdy.x) * invDet);\n"
	"        } else {\n"
	"            float3 gN0 = normalize(input.worldNormal);\n"
	"            Bt = normalize(cross(gN0, float3(0.0, 1.0, 0.0) + gN0 * 0.001));\n"
	"            T  = normalize(cross(Bt, gN0));\n"
	"        }\n"
	"        float3 gN = normalize(input.worldNormal);\n"
	"        T  = normalize(T - gN * dot(T, gN));\n"
	"        Bt = normalize(cross(gN, T));\n"
	"        float3 nrm = gNormal.Sample(gSmp1, input.uv0).xyz * 2.0 - 1.0;\n"
	"        if (dot(nrm, nrm) < 1e-8) { nrm = float3(0.0, 0.0, 1.0); } else { nrm = normalize(nrm); }\n"
	"        float strength = saturate(Params.y) * 1.8;\n"
	"        float3 Bf = dot(cross(T, Bt), gN) > 0.0 ? Bt : -Bt;\n"
	"        // Transform tangent-space normal to world space using the real TBN.\n"
	"        N = normalize(T * nrm.x + Bf * nrm.y + gN * nrm.z);\n"
	"        if (!all(isfinite(N))) { N = gN; }\n"
	"    }\n"
	"    float3 V = normalize(CameraPos.xyz - input.worldPos);\n"
	"    float3 L = normalize(SunDir.xyz);\n"
	"    float3 H = normalize(L + V);\n"
	"    float ndl = saturate(dot(N, L));\n"
	"    float ndv = saturate(dot(N, V));\n"
	"    // PBR parameters (driven by Params2).\n"
	"    float metalness = saturate(Params2.x);\n"
	"    float roughness = saturate(Params2.y);\n"
	"    roughness = max(roughness, 0.05);\n"
	"    float envStrength = saturate(Params2.z);\n"
	"    bool  enablePBR = (Params2.w > 0.5);\n"
	"    // F0: dielectric = 0.04, metal = base color.\n"
	"    float3 F0 = lerp(float3(0.04, 0.04, 0.04), base.rgb * MatTint.rgb, metalness);\n"
	"    float3 lit;\n"
	"    if (enablePBR) {\n"
	"        // Direct lighting (Cook-Torrance BRDF).\n"
	"        float3 F = FresnelSchlick(max(dot(H, V), 0.0), F0);\n"
	"        float  D = DistributionGGX(N, H, roughness);\n"
	"        float  G = GeometrySmith(N, V, L, roughness);\n"
	"        float3 specular = (D * G * F) / max(4.0 * ndv * ndl, 1e-4);\n"
	"        // Diffuse (metals have ~0 diffuse).\n"
	"        float3 kD = (1.0 - metalness) * (1.0 - F) / 3.14159;\n"
	"        float3 diffuse = kD * base.rgb * MatTint.rgb / 3.14159;\n"
	"        float3 direct = (diffuse + specular) * SunColor.rgb * ndl;\n"
	"        // Environment reflection (procedural sky, no cube map).\n"
	"        float3 R = reflect(-V, N);\n"
	"        float3 envColor = EnvSample(R);\n"
	"        float3 Fenv = FresnelSchlick(ndv, F0);\n"
	"        float3 reflection = envColor * Fenv * envStrength * (1.0 - roughness * roughness);\n"
	"        // Ambient term.\n"
	"        float3 ambient = AmbientColor.rgb * base.rgb * MatTint.rgb * (1.0 - metalness);\n"
	"        lit = ambient + direct + reflection;\n"
	"        // Blend with vertex-lit to preserve team tints.\n"
	"        lit = lerp(vtxLit, lit, 0.9);\n"
	"    } else {\n"
	"        // Non-PBR path: simple Lambert + Blinn-Phong.\n"
	"        float3 perPixel = base.rgb * MatTint.rgb * (AmbientColor.rgb + SunColor.rgb * ndl);\n"
	"        if (Params.z > 0.5) {\n"
	"            float3 H0 = normalize(L + V);\n"
	"            float ndh = saturate(dot(N, H0));\n"
	"            float spec = pow(ndh, Params.x) * SpecularColor.rgb;\n"
	"            perPixel += spec * ndl;\n"
	"        }\n"
	"        lit = lerp(vtxLit, perPixel, 0.85);\n"
	"    }\n"
	"    lit = max(lit, base.rgb * MatTint.rgb * 0.15f);\n"
	"    if (!all(isfinite(lit))) {\n"
	"        lit = vtxLit;\n"
	"    }\n"
	"    lit = saturate(lit);\n"
	"    if (Alpha.x > 0.5) {\n"
	"        if (Alpha.y > 0.5) { if (base.a > Alpha.z) discard; }\n"
	"        else              { if (base.a < Alpha.z) discard; }\n"
	"    }\n"
	"    if (FogEnable != 0u) {\n"
	"        float f = FogFactor(input.fog);\n"
	"        lit = lerp(FogColor.rgb, lit, f);\n"
	"    }\n"
	"    return float4(lit, base.a);\n"
	"}\n"
;

